# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://byz007.github.io/Helpseeker NBdev Preprocessing/"

git_url = "https://github.com/byz007/Helpseeker NBdev Preprocessing/tree/master/"

def custom_doc_links(name): return None
